### ISSUE TITLE
onClose were not fired on Safari

### ISSUE THREAD

**Issue by Momijiichigo** [woofers/react-dialog-polyfill#8]
When I run my code using this polyfill, the onClose listener had fired and worked properly on Chrome, but on Safari (both IOS and Mac) it did not. Could you fix that?

**Comment by Momijiichigo** [comment]
I solved the problem: https://stackoverflow.com/questions/64328260/react-onclose-eventlistener-not-fired-on-safari

I commented out the onCancel and onClose part below:
```javascript
return (
    <dialog {...rest}
     ref={modal}
     //onCancel={onCancelWrap}
     //onClose={onCloseWrap}
    >
      {children}
    </dialog>
  )
```
and add native event listener,
```javascript
useEffect(() => {
    const self = modal.current
    dialogPolyfill.registerDialog(self);
    self.onclose=e => {
      onClose(e, self)
    }
    self.oncancel=e => {
      e.preventDefault()
      onCancel(e, self)
    }
```
it worked on Safari. Maybe it is a problem with React.

**Comment by woofers** [comment]
@Momijiichigo Thats great to here.  I was looking at this earlier and had the same issue using the polyfill directly (without React).  It seems that the `onclose` event handler does not work in Safari with the polyfill yet the event listener does.

Not sure if its an issue with Safari or the polyfill.  Regarless I will see if I can patch this in a future release. 

Thanks again for opening the issue and I will keep it open until its resolved in the package.

**Comment by Momijiichigo** [comment]
Yes, Thanks!

**Comment by mattvv** [comment]
@woofers did you end up implementing this support for Safari? I'm seeing some odd things on Safari mobile

**Comment by woofers** [comment]
@mattvv Thanks for reminding me about this one.  

I previously thought it was an issue with the React synthetic events and the polyfill, but looking at this again just now it seemed like it was due to the fact that Safari will not hide dialogs without the `show` attribute like Firefox will (which has [partial Dialog support](https://caniuse.com/dialog)). Then when the `close` method is called twice, Safari will just error.

I just released `v1.0.6` which includes ceff48c that injects some CSS to hide the dialog when closed in Safari.  There is more CSS that `dialog-polyfill` includes [here](https://github.com/GoogleChrome/dialog-polyfill/blob/master/dialog-polyfill.css), but for now I just included the portion to hide the dialog but you can add it if needed. 

Let me know if this solved the issues.

**Comment by mattvv** [comment]
Thanks @woofers I'll test this today!

**Comment by mattvv** [comment]
@woofers this works perfectly for me on Safari Mobile now! Thanks for this! Super fast response!

**Comment by woofers** [comment]
@mattvv No worries, thanks for pinging me on the issue.  Going to finally close this out :sweat_smile:
